name: Build and Upload Paper PDF

on:
  push:
    paths:
      - 'paper/paper.md'
  pull_request:
    paths:
      - 'paper/paper.md'

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Cache texlive packages to speed up build
      - name: Cache TeX Live
        uses: actions/cache@v3
        with:
          path: /usr/share/texlive
          key: ${{ runner.os }}-texlive

      # Step 3: Install dependencies
      - name: Install Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended texlive-latex-extra

      # Step 4: Convert Markdown to PDF with verbose output
      - name: Generate PDF from paper.md
        run: pandoc paper/paper.md -o paper/paper.pdf --verbose

      # Step 5: Upload PDF as artifact
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: research-paper
          path: paper/paper.pdf

